name: accelerometer_flutter_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

flutter:
  uses-material-design: true
  assets:
    - .env

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.0
  flutter_secure_storage: ^8.0.0
  geolocator: ^9.0.0
  flutter_blue: ^0.8.0
  csv: ^5.0.0
  google_maps_flutter: ^2.0.0
  flutter_dotenv: ^5.0.0
  sensors_plus: ^5.0.1
  path_provider: ^2.1.3
  cupertino_icons: ^1.0.6
  http: ^0.13.3  # HTTPリクエスト用パッケージ
  permission_handler: ^8.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter